### ISSUE TITLE
Unsupported processor architecture: AARCH64

### ISSUE THREAD

**Issue by ngenetzky-appareo** [NikosMouzakitis/QEMU_BOOT_aarch64_atf_edk2_firmware#1]
I was attempting to compile with the "-a AARCH64" as you described in your document . It seems like the code is indicating that architecture is not supported. Based on this code from the build script: https://github.com/tianocore/edk2/blob/b24306f15daa2ff8510b06702114724b33895d3c/OvmfPkg/build.sh#L122-L125

Could you elaborate a little about the steps you did?

https://github.com/NikosMouzakitis/QEMU_BOOT_aarch64_atf_edk2_firmware/blob/62387dbf4cf3f9e09d451552f12b1cbf7c254551/README.md?plain=1#L50-L56

NOTE: I originally found the article via LinkedIn: https://www.linkedin.com/pulse/qemu-boot-aarch64-atfarm-trusted-firmware-edk2-nikos-mouzakitis/

My primary github is @ngenetzky and LinkedIn is https://www.linkedin.com/in/genetzky/.

**Comment by NikosMouzakitis** [comment]
Hello @ngenetzky-appareo it is possible to compile edk2 for the aarch64 architecture as in this tutorial.
Have you tried to reproduce the steps here and on the "build" command  you encountered some kind of mistake- error?

**Comment by NGenetzky** [comment]
@NikosMouzakitis , yes I repeated your command verbatim and was able to compile. The issue I face is that I am trying to compile inside of a yocto recipe. I might try to call 'build' (`edk2/BaseTools/BinWrappers/PosixLike/build` ) directly).

FYI. The following installs were required to compile from a vanilla debian docker image:

`apt install build-essential gcc-aarch64-linux-gnu iasl python-is-python3 python3 uuid-dev`
